// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: cql/commons.proto

package cql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataType int32

const (
	DataType_BOOL   DataType = 0
	DataType_BYTES  DataType = 1
	DataType_INT    DataType = 2
	DataType_LONG   DataType = 3
	DataType_FLOAT  DataType = 4
	DataType_DOUBLE DataType = 5
	DataType_STRING DataType = 6
	DataType_JSON   DataType = 7
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "BOOL",
		1: "BYTES",
		2: "INT",
		3: "LONG",
		4: "FLOAT",
		5: "DOUBLE",
		6: "STRING",
		7: "JSON",
	}
	DataType_value = map[string]int32{
		"BOOL":   0,
		"BYTES":  1,
		"INT":    2,
		"LONG":   3,
		"FLOAT":  4,
		"DOUBLE": 5,
		"STRING": 6,
		"JSON":   7,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_cql_commons_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_cql_commons_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_cql_commons_proto_rawDescGZIP(), []int{0}
}

type DataPacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DataType  DataType `protobuf:"varint,2,opt,name=dataType,proto3,enum=cql.DataType" json:"dataType,omitempty"`
	BoolVal   bool     `protobuf:"varint,16,opt,name=boolVal,proto3" json:"boolVal,omitempty"`
	BytesVal  []byte   `protobuf:"bytes,17,opt,name=bytesVal,proto3" json:"bytesVal,omitempty"`
	S32IntVal int32    `protobuf:"zigzag32,18,opt,name=s32intVal,proto3" json:"s32intVal,omitempty"`
	S64IntVal int64    `protobuf:"zigzag64,19,opt,name=s64intVal,proto3" json:"s64intVal,omitempty"`
	FloatVal  float32  `protobuf:"fixed32,20,opt,name=floatVal,proto3" json:"floatVal,omitempty"`
	DoubleVal float64  `protobuf:"fixed64,21,opt,name=doubleVal,proto3" json:"doubleVal,omitempty"`
	StringVal string   `protobuf:"bytes,22,opt,name=stringVal,proto3" json:"stringVal,omitempty"`
	JsonVal   []byte   `protobuf:"bytes,23,opt,name=jsonVal,proto3" json:"jsonVal,omitempty"`
}

func (x *DataPacket) Reset() {
	*x = DataPacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cql_commons_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPacket) ProtoMessage() {}

func (x *DataPacket) ProtoReflect() protoreflect.Message {
	mi := &file_cql_commons_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPacket.ProtoReflect.Descriptor instead.
func (*DataPacket) Descriptor() ([]byte, []int) {
	return file_cql_commons_proto_rawDescGZIP(), []int{0}
}

func (x *DataPacket) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DataPacket) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_BOOL
}

func (x *DataPacket) GetBoolVal() bool {
	if x != nil {
		return x.BoolVal
	}
	return false
}

func (x *DataPacket) GetBytesVal() []byte {
	if x != nil {
		return x.BytesVal
	}
	return nil
}

func (x *DataPacket) GetS32IntVal() int32 {
	if x != nil {
		return x.S32IntVal
	}
	return 0
}

func (x *DataPacket) GetS64IntVal() int64 {
	if x != nil {
		return x.S64IntVal
	}
	return 0
}

func (x *DataPacket) GetFloatVal() float32 {
	if x != nil {
		return x.FloatVal
	}
	return 0
}

func (x *DataPacket) GetDoubleVal() float64 {
	if x != nil {
		return x.DoubleVal
	}
	return 0
}

func (x *DataPacket) GetStringVal() string {
	if x != nil {
		return x.StringVal
	}
	return ""
}

func (x *DataPacket) GetJsonVal() []byte {
	if x != nil {
		return x.JsonVal
	}
	return nil
}

var File_cql_commons_proto protoreflect.FileDescriptor

var file_cql_commons_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x71, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x71, 0x6c, 0x22, 0xad, 0x02, 0x0a, 0x0a, 0x44, 0x61, 0x74,
	0x61, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x08, 0x64, 0x61, 0x74,
	0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x63, 0x71,
	0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x73, 0x56, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x33,
	0x32, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x12, 0x20, 0x01, 0x28, 0x11, 0x52, 0x09, 0x73,
	0x33, 0x32, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x36, 0x34, 0x69,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x18, 0x13, 0x20, 0x01, 0x28, 0x12, 0x52, 0x09, 0x73, 0x36, 0x34,
	0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56,
	0x61, 0x6c, 0x18, 0x14, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56,
	0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x18, 0x16, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x6a, 0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x18, 0x17, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x6a, 0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x2a, 0x5f, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54,
	0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c,
	0x45, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x06, 0x12,
	0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x07, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x68, 0x72, 0x65, 0x79, 0x62, 0x61, 0x74,
	0x72, 0x61, 0x2f, 0x63, 0x72, 0x61, 0x6e, 0x6b, 0x64, 0x62, 0x2f, 0x63, 0x71, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cql_commons_proto_rawDescOnce sync.Once
	file_cql_commons_proto_rawDescData = file_cql_commons_proto_rawDesc
)

func file_cql_commons_proto_rawDescGZIP() []byte {
	file_cql_commons_proto_rawDescOnce.Do(func() {
		file_cql_commons_proto_rawDescData = protoimpl.X.CompressGZIP(file_cql_commons_proto_rawDescData)
	})
	return file_cql_commons_proto_rawDescData
}

var file_cql_commons_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cql_commons_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cql_commons_proto_goTypes = []interface{}{
	(DataType)(0),      // 0: cql.DataType
	(*DataPacket)(nil), // 1: cql.DataPacket
}
var file_cql_commons_proto_depIdxs = []int32{
	0, // 0: cql.DataPacket.dataType:type_name -> cql.DataType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cql_commons_proto_init() }
func file_cql_commons_proto_init() {
	if File_cql_commons_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cql_commons_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataPacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cql_commons_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cql_commons_proto_goTypes,
		DependencyIndexes: file_cql_commons_proto_depIdxs,
		EnumInfos:         file_cql_commons_proto_enumTypes,
		MessageInfos:      file_cql_commons_proto_msgTypes,
	}.Build()
	File_cql_commons_proto = out.File
	file_cql_commons_proto_rawDesc = nil
	file_cql_commons_proto_goTypes = nil
	file_cql_commons_proto_depIdxs = nil
}
